import type { AssetKind, CatalogItem, CategoryId, EnvPreset } from "./types";

const shape = (
  key: string,
  label: string,
  min: number,
  max: number,
  step = 0.05,
): CatalogItem["params"][number] => ({
  key,
  label,
  type: "range",
  min,
  max,
  step,
});

export const CATEGORIES: { id: CategoryId; label: string }[] = [
  { id: "photo", label: "Photos" },
  { id: "vehicle", label: "Vehicles" },
  { id: "building", label: "Buildings" },
  { id: "nature", label: "Nature" },
  { id: "furniture", label: "Furniture" },
  { id: "prop", label: "Props" },
  { id: "primitive", label: "Primitives" },
];

export const ENV_PRESETS: { id: EnvPreset; label: string }[] = [
  { id: "studio", label: "Studio" },
  { id: "sunset", label: "Sunset" },
  { id: "warehouse", label: "Warehouse" },
  { id: "night", label: "Night" },
  { id: "city", label: "City" },
  { id: "forest", label: "Forest" },
];

export const BODY_SWATCHES = [
  "#f4f4f5",
  "#d4d4d8",
  "#71717a",
  "#27272a",
  "#18181b",
  "#b42318",
  "#9a3412",
  "#1e3a5f",
  "#164e3b",
  "#e7e0d4",
] as const;

export const ACCENT_SWATCHES = [
  "#f4f4f5",
  "#a1a1aa",
  "#3f3f46",
  "#18181b",
  "#1e3a5f",
  "#7f1d1d",
  "#365314",
  "#0f172a",
] as const;

export const CATALOG: CatalogItem[] = [
  {
    id: "sports-car",
    name: "Sports car",
    category: "vehicle",
    blurb: "Low coupe with a cabin bubble and rear wing.",
    defaults: { length: 1, width: 1, height: 1, ride: 1, wheel: 1 },
    params: [
      shape("length", "Length", 0.8, 1.35),
      shape("width", "Width", 0.85, 1.25),
      shape("height", "Body height", 0.8, 1.3),
      shape("ride", "Ride height", 0.7, 1.4),
      shape("wheel", "Wheel size", 0.75, 1.3),
    ],
  },
  {
    id: "sedan",
    name: "Sedan",
    category: "vehicle",
    blurb: "Four-door daily with a longer cabin.",
    defaults: { length: 1, width: 1, height: 1, ride: 1, wheel: 1 },
    params: [
      shape("length", "Length", 0.85, 1.3),
      shape("width", "Width", 0.85, 1.2),
      shape("height", "Body height", 0.85, 1.3),
      shape("ride", "Ride height", 0.75, 1.35),
      shape("wheel", "Wheel size", 0.8, 1.25),
    ],
  },
  {
    id: "suv",
    name: "SUV",
    category: "vehicle",
    blurb: "Tall wagon with roof rails and a high beltline.",
    defaults: { length: 1, width: 1, height: 1, ride: 1, wheel: 1 },
    params: [
      shape("length", "Length", 0.85, 1.25),
      shape("width", "Width", 0.9, 1.25),
      shape("height", "Body height", 0.85, 1.35),
      shape("ride", "Ride height", 0.8, 1.4),
      shape("wheel", "Wheel size", 0.85, 1.3),
    ],
  },
  {
    id: "pickup",
    name: "Pickup",
    category: "vehicle",
    blurb: "Cab plus open bed, ready for cargo.",
    defaults: { length: 1, width: 1, height: 1, ride: 1, wheel: 1 },
    params: [
      shape("length", "Length", 0.85, 1.3),
      shape("width", "Width", 0.9, 1.25),
      shape("height", "Cab height", 0.85, 1.3),
      shape("ride", "Ride height", 0.8, 1.4),
      shape("wheel", "Wheel size", 0.85, 1.3),
    ],
  },
  {
    id: "van",
    name: "Van",
    category: "vehicle",
    blurb: "Boxy panel van with a tall greenhouse.",
    defaults: { length: 1, width: 1, height: 1, ride: 1, wheel: 1 },
    params: [
      shape("length", "Length", 0.85, 1.3),
      shape("width", "Width", 0.9, 1.25),
      shape("height", "Body height", 0.85, 1.35),
      shape("ride", "Ride height", 0.8, 1.3),
      shape("wheel", "Wheel size", 0.8, 1.25),
    ],
  },
  {
    id: "modern-house",
    name: "Modern house",
    category: "building",
    blurb: "Offset volumes, ribbon windows, flat overhang.",
    defaults: { width: 1, depth: 1, stories: 1, roof: 1 },
    params: [
      shape("width", "Width", 0.75, 1.4),
      shape("depth", "Depth", 0.75, 1.4),
      shape("stories", "Massing", 0.8, 1.45),
      shape("roof", "Overhang", 0.6, 1.5),
    ],
  },
  {
    id: "cottage",
    name: "Cottage",
    category: "building",
    blurb: "Gable roof, chimney, and a centered door.",
    defaults: { width: 1, depth: 1, stories: 1, roof: 1 },
    params: [
      shape("width", "Width", 0.8, 1.35),
      shape("depth", "Depth", 0.8, 1.35),
      shape("stories", "Wall height", 0.8, 1.4),
      shape("roof", "Roof pitch", 0.65, 1.5),
    ],
  },
  {
    id: "cabin",
    name: "Cabin",
    category: "building",
    blurb: "Timber lodge with a deep porch.",
    defaults: { width: 1, depth: 1, stories: 1, roof: 1 },
    params: [
      shape("width", "Width", 0.8, 1.35),
      shape("depth", "Depth", 0.8, 1.4),
      shape("stories", "Wall height", 0.8, 1.35),
      shape("roof", "Roof pitch", 0.7, 1.45),
    ],
  },
  {
    id: "tower",
    name: "Tower",
    category: "building",
    blurb: "Stepped keep with a pointed cap.",
    defaults: { width: 1, depth: 1, stories: 1, roof: 1 },
    params: [
      shape("width", "Width", 0.8, 1.3),
      shape("depth", "Depth", 0.8, 1.3),
      shape("stories", "Height", 0.75, 1.5),
      shape("roof", "Cap", 0.7, 1.4),
    ],
  },
  {
    id: "shop",
    name: "Shop",
    category: "building",
    blurb: "Storefront, awning, and a display window.",
    defaults: { width: 1, depth: 1, stories: 1, roof: 1 },
    params: [
      shape("width", "Width", 0.8, 1.4),
      shape("depth", "Depth", 0.75, 1.35),
      shape("stories", "Height", 0.8, 1.4),
      shape("roof", "Awning", 0.6, 1.4),
    ],
  },
  {
    id: "oak",
    name: "Oak",
    category: "nature",
    blurb: "Broad canopy on a branching trunk.",
    defaults: { height: 1, fullness: 1, seed: 42 },
    params: [
      shape("height", "Height", 0.7, 1.5),
      shape("fullness", "Canopy", 0.65, 1.4),
      shape("seed", "Form", 1, 200, 1),
    ],
  },
  {
    id: "pine",
    name: "Pine",
    category: "nature",
    blurb: "Stacked cones on a straight trunk.",
    defaults: { height: 1, fullness: 1, seed: 12 },
    params: [
      shape("height", "Height", 0.7, 1.55),
      shape("fullness", "Density", 0.7, 1.4),
      shape("seed", "Form", 1, 200, 1),
    ],
  },
  {
    id: "palm",
    name: "Palm",
    category: "nature",
    blurb: "Tall trunk with a fan of fronds.",
    defaults: { height: 1, fullness: 1, seed: 7 },
    params: [
      shape("height", "Height", 0.7, 1.55),
      shape("fullness", "Fronds", 0.7, 1.4),
      shape("seed", "Form", 1, 200, 1),
    ],
  },
  {
    id: "willow",
    name: "Willow",
    category: "nature",
    blurb: "Drooping curtains of foliage.",
    defaults: { height: 1, fullness: 1, seed: 19 },
    params: [
      shape("height", "Height", 0.7, 1.45),
      shape("fullness", "Curtain", 0.7, 1.4),
      shape("seed", "Form", 1, 200, 1),
    ],
  },
  {
    id: "rock",
    name: "Boulder",
    category: "nature",
    blurb: "Faceted stone cluster for terrain.",
    defaults: { height: 1, fullness: 1, seed: 5 },
    params: [
      shape("height", "Scale", 0.6, 1.6),
      shape("fullness", "Chunkiness", 0.7, 1.4),
      shape("seed", "Form", 1, 200, 1),
    ],
  },
  {
    id: "chair",
    name: "Chair",
    category: "furniture",
    blurb: "Four-leg chair with a slatted back.",
    defaults: { width: 1, depth: 1, height: 1 },
    params: [
      shape("width", "Width", 0.8, 1.3),
      shape("depth", "Depth", 0.8, 1.3),
      shape("height", "Back height", 0.8, 1.4),
    ],
  },
  {
    id: "table",
    name: "Table",
    category: "furniture",
    blurb: "Simple dining table on four legs.",
    defaults: { width: 1, depth: 1, height: 1 },
    params: [
      shape("width", "Length", 0.75, 1.5),
      shape("depth", "Width", 0.75, 1.4),
      shape("height", "Height", 0.8, 1.3),
    ],
  },
  {
    id: "sofa",
    name: "Sofa",
    category: "furniture",
    blurb: "Three-seat lounge with rolled arms.",
    defaults: { width: 1, depth: 1, height: 1 },
    params: [
      shape("width", "Length", 0.8, 1.4),
      shape("depth", "Depth", 0.8, 1.3),
      shape("height", "Back height", 0.8, 1.35),
    ],
  },
  {
    id: "lamp",
    name: "Floor lamp",
    category: "furniture",
    blurb: "Stem lamp with a glowing shade.",
    defaults: { width: 1, depth: 1, height: 1 },
    params: [
      shape("width", "Shade", 0.75, 1.4),
      shape("height", "Height", 0.75, 1.45),
      shape("depth", "Base", 0.8, 1.3),
    ],
  },
  {
    id: "shelf",
    name: "Bookshelf",
    category: "furniture",
    blurb: "Open case with four boards.",
    defaults: { width: 1, depth: 1, height: 1 },
    params: [
      shape("width", "Width", 0.8, 1.4),
      shape("depth", "Depth", 0.8, 1.3),
      shape("height", "Height", 0.8, 1.45),
    ],
  },
  {
    id: "crate",
    name: "Crate",
    category: "prop",
    blurb: "Banded shipping crate — a game staple.",
    defaults: { size: 1, band: 1 },
    params: [shape("size", "Size", 0.7, 1.5), shape("band", "Bands", 0.6, 1.4)],
  },
  {
    id: "barrel",
    name: "Barrel",
    category: "prop",
    blurb: "Staved drum with metal hoops.",
    defaults: { size: 1, band: 1 },
    params: [shape("size", "Size", 0.7, 1.5), shape("band", "Belly", 0.75, 1.3)],
  },
  {
    id: "traffic-cone",
    name: "Traffic cone",
    category: "prop",
    blurb: "Safety cone with a square base.",
    defaults: { size: 1, band: 1 },
    params: [shape("size", "Size", 0.7, 1.5), shape("band", "Stripe", 0.7, 1.3)],
  },
  {
    id: "hydrant",
    name: "Hydrant",
    category: "prop",
    blurb: "Street hydrant with side caps.",
    defaults: { size: 1, band: 1 },
    params: [shape("size", "Size", 0.75, 1.4), shape("band", "Bulk", 0.8, 1.3)],
  },
  {
    id: "vase",
    name: "Vase",
    category: "prop",
    blurb: "Lathed vessel with a flared lip.",
    defaults: { size: 1, band: 1 },
    params: [shape("size", "Height", 0.7, 1.5), shape("band", "Belly", 0.65, 1.45)],
  },
  {
    id: "box",
    name: "Box",
    category: "primitive",
    blurb: "Rounded box — the universal game block.",
    defaults: { sizeX: 1, sizeY: 1, sizeZ: 1 },
    params: [
      shape("sizeX", "Width", 0.4, 2),
      shape("sizeY", "Height", 0.4, 2),
      shape("sizeZ", "Depth", 0.4, 2),
    ],
  },
  {
    id: "sphere",
    name: "Sphere",
    category: "primitive",
    blurb: "Smooth ball for props and placeholders.",
    defaults: { sizeX: 1, sizeY: 1, sizeZ: 1 },
    params: [shape("sizeX", "Radius", 0.4, 1.8)],
  },
  {
    id: "cylinder",
    name: "Cylinder",
    category: "primitive",
    blurb: "Column, pipe, or pedestal.",
    defaults: { sizeX: 1, sizeY: 1, sizeZ: 1 },
    params: [
      shape("sizeX", "Radius", 0.4, 1.6),
      shape("sizeY", "Height", 0.4, 2),
    ],
  },
  {
    id: "torus",
    name: "Torus",
    category: "primitive",
    blurb: "Ring — tires, portals, hoops.",
    defaults: { sizeX: 1, sizeY: 1, sizeZ: 1 },
    params: [
      shape("sizeX", "Radius", 0.5, 1.6),
      shape("sizeY", "Tube", 0.5, 1.6),
    ],
  },
  {
    id: "capsule",
    name: "Capsule",
    category: "primitive",
    blurb: "Rounded pill, useful as a stand-in body.",
    defaults: { sizeX: 1, sizeY: 1, sizeZ: 1 },
    params: [
      shape("sizeX", "Radius", 0.5, 1.5),
      shape("sizeY", "Length", 0.5, 2),
    ],
  },
  {
    id: "photo-relief",
    name: "Photo sculpt",
    category: "photo",
    blurb: "A photograph lifted into a 3D relief you can light and export.",
    defaults: { depth: 0.38, cutout: 1, thickness: 0.1 },
    params: [
      shape("depth", "Relief", 0.05, 1.2),
      shape("cutout", "Knockout", 0.55, 1, 0.01),
      shape("thickness", "Thickness", 0, 0.35),
    ],
  },
];

export const CATALOG_BY_ID: Record<AssetKind, CatalogItem> = Object.fromEntries(
  CATALOG.map((item) => [item.id, item]),
) as Record<AssetKind, CatalogItem>;

export function itemsIn(category: CategoryId) {
  return CATALOG.filter((item) => item.category === category);
}
