/** Live MT World gallery — dress looks hosted on the MT stack. */
export const MT_WORLD_ORIGIN = "https://memetorrent.futuret3ch.com.au";

export const CAST_LOOKS: { id: string; name: string }[] = [
  { id: "nova", name: "Nova" },
  { id: "rex", name: "Rex" },
  { id: "mira", name: "Mira" },
  { id: "kai", name: "Kai" },
  { id: "sol", name: "Sol" },
  { id: "jade", name: "Jade" },
  { id: "omar", name: "Omar" },
  { id: "vex", name: "Vex" },
  { id: "bo", name: "Bo" },
  { id: "zara", name: "Zara" },
  { id: "rhea", name: "Rhea" },
  { id: "idris", name: "Idris" },
  { id: "yuki", name: "Yuki" },
  { id: "cruz", name: "Cruz" },
  { id: "amara", name: "Amara" },
  { id: "flynn", name: "Flynn" },
  { id: "noor", name: "Noor" },
  { id: "theo", name: "Theo" },
  { id: "lila", name: "Lila" },
  { id: "kenji", name: "Kenji" },
  { id: "sable", name: "Sable" },
  { id: "oren", name: "Oren" },
  { id: "minh", name: "Minh" },
  { id: "freya", name: "Freya" },
  { id: "dante", name: "Dante" },
  { id: "priya", name: "Priya" },
  { id: "malik", name: "Malik" },
  { id: "quinn", name: "Quinn" },
  { id: "bea", name: "Bea" },
  { id: "hugo", name: "Hugo" },
  { id: "ines", name: "Ines" },
  { id: "jace", name: "Jace" },
  { id: "kira", name: "Kira" },
  { id: "leon", name: "Leon" },
  { id: "mae", name: "Mae" },
  { id: "nico", name: "Nico" },
  { id: "odette", name: "Odette" },
  { id: "pax", name: "Pax" },
  { id: "rumi", name: "Rumi" },
  { id: "seth", name: "Seth" },
  { id: "tia", name: "Tia" },
  { id: "ulrich", name: "Ulrich" },
  { id: "vera", name: "Vera" },
  { id: "wynn", name: "Wynn" },
  { id: "xiao", name: "Xiao" },
  { id: "yasmin", name: "Yasmin" },
  { id: "zed", name: "Zed" },
  { id: "anouk", name: "Anouk" },
  { id: "bodhi", name: "Bodhi" },
  { id: "nyx", name: "Nyx" },
];

export function castFaceUrl(id: string) {
  return `${MT_WORLD_ORIGIN}/games/gallery/cast/${id}.jpg`;
}
